# Generated by Django 4.0.5 on 2022-07-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='paymentDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Chas', 'Chas'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Paytm', 'Paytm')], max_length=100)),
                ('payment_date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.student')),
            ],
        ),
    ]
