# Generated by Django 4.0.5 on 2022-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mobileno', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
